### ISSUE TITLE
automatic builds on Windows

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1]
This repo seems to have it already implemented by @pjb7687 : https://github.com/pjb7687/GNU-Data-Language-0.9.6

**Comment by slayoo** [comment]
@pjb7687 would you have time to try to import the Windows build scripts for GDL to this repo? Thanks!

**Comment by pjb7687** [comment]
@slayoo It once worked with Drone CI but unfortunately it is discontinued, so it doesn't work. Maybe I can try similar configuration with Travis CI instead. I have no idea whether it supports building in Docker container with msys32 ??

**Comment by pjb7687** [comment]
I will try it in this weekend.

**Comment by slayoo** [comment]
thank you!
There is also the AppVeyor platform. I do have some experience with it, but I have no experience buidling GDL in Windows, hence I didn't go too far trying with it, but in case this could be of some help, here's the appveyor.yml file I've tried with:
```
platform:
  - x86
  - x64

init:
  - ps: |
        If ($env:platform -Match "x86") {
          $env:CMAKE_GEN_PLAT="Win32"
          $env:PYTHON_ROOT="C:\Python27"
        } Else {
          $env:CMAKE_GEN_PLAT="x64"
          $env:PYTHON_ROOT="C:\Python27-x64"
        }
  - cmd: C:/"Program Files (x86)"/"Microsoft Visual Studio 12.0"/VC/vcvarsall.bat

install:
  # <TEMPORARY>
  - ps: wget https://github.com/gnudatalanguage/gdl/archive/master.zip -OutFile master.zip
  - 7z x master.zip
  # </TEMPORARY>

  #- choco upgrade cmake # so newer Boost versions are supported
  #- set path=C:\Program Files\CMake\bin;%path%

  #- ps: wget http://bitbucket.org/eigen/eigen/get/3.3.2.zip -OutFile eigen.zip
  #- 7z x eigen.zip -o"C:\projects" -y > nul

  #- set path=%PYTHON_ROOT%;%path%
  #- python -m pip install numpy

before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"

build_script:
  # <TEMPORARY>
  - cd gdl-master/gdl
  # </TEMPORARY>
  - ps: $env:CMAKE_ARGS = '-DEIGEN3_INCLUDE_DIR="C:\projects\eigen-eigen-da9b4e14c255" -DEDITLINE=no -DREADLINE=no'

  - md build
  - cd build
  - cmake .. %CMAKE_ARGS% -DCMAKE_GENERATOR_PLATFORM="%CMAKE_GEN_PLAT%" -DPYTHON_EXECUTABLE=%PYTHON_ROOT%\python.exe -DPYTHON_INCLUDE_DIR=%PYTHON_ROOT%\include
  - set path_orig=%path%

  - cmake --build . --config Debug
  - cmake --build . --config Release

  - ctest -C Debug --output-on-failure
  - ctest -C Release --output-on-failure

  - cmake --build . --target install
  - python -c "import gdl; dir(gdl)"
```

and here is the log:

https://ci.appveyor.com/project/slayoo/ci-tests/build/1.0.4
